-- =============================================================================
-- Audit.RI_Check_Config -- seed (fact fk -> target pk relationships to RI-check)
-- =============================================================================
-- Generated from live Gold metadata, then hand-corrected (fk_Site -> Dim_Practice_Sites;
-- fact-to-fact journey refs fk_Appointment_* excluded). Regenerate the base list with:
--   SELECT ft.name Fact, fc.name FK, dp.Dim, dp.PK FROM sys.tables ft
--   JOIN sys.schemas fs ON fs.schema_id=ft.schema_id JOIN sys.columns fc ON fc.object_id=ft.object_id
--   LEFT JOIN (SELECT dt.name Dim, dc.name PK FROM sys.tables dt JOIN sys.schemas ds ON ds.schema_id=dt.schema_id
--     JOIN sys.columns dc ON dc.object_id=dt.object_id WHERE ds.name='Gold' AND dt.name LIKE 'Dim[_]%' AND dc.name LIKE 'pk[_]%') dp
--     ON dp.PK='pk_'+SUBSTRING(fc.name,4,128)
--   WHERE fs.name='Gold' AND (ft.name LIKE 'Fact[_]%' OR ft.name LIKE 'Aggregate[_]%') AND fc.name LIKE 'fk[_]%';
-- (Run client-side; sys.* is not queryable inside a Fabric proc.)
-- =============================================================================
DELETE FROM Audit.RI_Check_Config;
GO
INSERT INTO Audit.RI_Check_Config (Fact_Table, FK_Column, Dim_Table, PK_Column, Is_Active) VALUES
 ('Aggregate_Practitioner_Contribution','fk_Date','Dim_Date','pk_Date',1),
 ('Aggregate_Practitioner_Contribution','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Aggregate_Practitioner_Contribution','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Aggregate_Site_Patient_Current','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Aggregate_Site_Patient_Current','fk_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Aggregate_Site_Patient_Practitioner_Daily','fk_Date','Dim_Date','pk_Date',1),
 ('Aggregate_Site_Patient_Practitioner_Daily','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Aggregate_Site_Patient_Practitioner_Daily','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Aggregate_Site_Patient_Practitioner_Daily','fk_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Aggregate_Site_Practitioner_Current','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Aggregate_Site_Practitioner_Current','fk_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Appointment_Journey','fk_Date_Start','Dim_Date','pk_Date',1),
 ('Fact_Appointment_Journey','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Appointment_Journey','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Appointment_Journey','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Appointments','fk_Cancellation_Reason','Dim_Cancellation_Reasons','pk_Cancellation_Reason',1),
 ('Fact_Appointments','fk_Date_Created','Dim_Date','pk_Date',1),
 ('Fact_Appointments','fk_Date_Pending','Dim_Date','pk_Date',1),
 ('Fact_Appointments','fk_Date_Start','Dim_Date','pk_Date',1),
 ('Fact_Appointments','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Appointments','fk_Payment_Plan','Dim_Payment_Plans','pk_Payment_Plan',1),
 ('Fact_Appointments','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Appointments','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Appointments','fk_User','Dim_Users','pk_User',1),
 ('Fact_Contracts','fk_Date_End','Dim_Date','pk_Date',1),
 ('Fact_Contracts','fk_Date_Start','Dim_Date','pk_Date',1),
 ('Fact_Contracts','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Daily_Targets','fk_Date','Dim_Date','pk_Date',1),
 ('Fact_Daily_Targets','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Daily_Targets','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Effective_Targets','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Effective_Targets','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Finance','fk_Date','Dim_Date','pk_Date',1),
 ('Fact_Finance','fk_GL_Account','Dim_GL_Account','pk_GL_Account',1),
 ('Fact_Finance','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Invoice_Items','fk_Account','Dim_Accounts','pk_Account',1),
 ('Fact_Invoice_Items','fk_Date_Created','Dim_Date','pk_Date',1),
 ('Fact_Invoice_Items','fk_Date_Invoice','Dim_Date','pk_Date',1),
 ('Fact_Invoice_Items','fk_Invoice','Dim_Invoices','pk_Invoice',1),
 ('Fact_Invoice_Items','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Invoice_Items','fk_Payment_Plan','Dim_Payment_Plans','pk_Payment_Plan',1),
 ('Fact_Invoice_Items','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Invoice_Items','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Invoice_Items','fk_Treatment','Dim_Treatments','pk_Treatment',1),
 ('Fact_Invoice_Items','fk_Treatment_Plan','Dim_Treatment_Plans','pk_Treatment_Plan',1),
 ('Fact_Invoice_Items','fk_User','Dim_Users','pk_User',1),
 ('Fact_Invoices','fk_Account','Dim_Accounts','pk_Account',1),
 ('Fact_Invoices','fk_Date_Due','Dim_Date','pk_Date',1),
 ('Fact_Invoices','fk_Date_Invoice','Dim_Date','pk_Date',1),
 ('Fact_Invoices','fk_Date_Paid','Dim_Date','pk_Date',1),
 ('Fact_Invoices','fk_Invoice','Dim_Invoices','pk_Invoice',1),
 ('Fact_Invoices','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Invoices','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Invoices','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Invoices','fk_User','Dim_Users','pk_User',1),
 ('Fact_KPI_Snapshot','fk_Date','Dim_Date','pk_Date',1),
 ('Fact_KPI_Snapshot','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_KPI_Snapshot','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Metric_Actuals','fk_Date','Dim_Date','pk_Date',1),
 ('Fact_Metric_Actuals','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Metric_Actuals','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_NHS_Claims','fk_Date_Approval','Dim_Date','pk_Date',1),
 ('Fact_NHS_Claims','fk_Date_Submitted','Dim_Date','pk_Date',1),
 ('Fact_NHS_Claims','fk_NHS_Contract','Dim_NHS_Contracts','pk_NHS_Contract',1),
 ('Fact_NHS_Claims','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_NHS_Claims','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_NHS_Claims','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_NHS_Claims','fk_Treatment_Plan','Dim_Treatment_Plans','pk_Treatment_Plan',1),
 ('Fact_NHS_Contract_Week','fk_Date_Week_Start','Dim_Date','pk_Date',1),
 ('Fact_NHS_Contract_Week','fk_NHS_Contract','Dim_NHS_Contracts','pk_NHS_Contract',1),
 ('Fact_NHS_Contract_Week','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_NHS_Contract_Week','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Payments','fk_Date_Payment','Dim_Date','pk_Date',1),
 ('Fact_Payments','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Payments','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Payments','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Practitioner_Diaries','fk_Date_Day','Dim_Date','pk_Date',1),
 ('Fact_Practitioner_Diaries','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Recalls','fk_Date_Appt_Booked','Dim_Date','pk_Date',1),
 ('Fact_Recalls','fk_Date_Due','Dim_Date','pk_Date',1),
 ('Fact_Recalls','fk_Date_First_Reminder','Dim_Date','pk_Date',1),
 ('Fact_Recalls','fk_Date_Last_Reminded','Dim_Date','pk_Date',1),
 ('Fact_Recalls','fk_Date_Run','Dim_Date','pk_Date',1),
 ('Fact_Recalls','fk_Date_Second_Reminder','Dim_Date','pk_Date',1),
 ('Fact_Recalls','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Targets','fk_Date','Dim_Date','pk_Date',1),
 ('Fact_Targets','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Targets','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Treatment_Appointments','fk_Date_Appointment','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Appointments','fk_Date_Created','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Appointments','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Treatment_Appointments','fk_Treatment_Plan','Dim_Treatment_Plans','pk_Treatment_Plan',1),
 ('Fact_Treatment_Plan_Items','fk_Date_Completed','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Plan_Items','fk_Date_Created','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Plan_Items','fk_Date_Updated','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Plan_Items','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Treatment_Plan_Items','fk_Payment_Plan','Dim_Payment_Plans','pk_Payment_Plan',1),
 ('Fact_Treatment_Plan_Items','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Treatment_Plan_Items','fk_Treatment','Dim_Treatments','pk_Treatment',1),
 ('Fact_Treatment_Plan_Items','fk_Treatment_Plan','Dim_Treatment_Plans','pk_Treatment_Plan',1),
 ('Fact_Treatment_Plans','fk_Date_Completed','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Plans','fk_Date_Created','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Plans','fk_Date_Start','Dim_Date','pk_Date',1),
 ('Fact_Treatment_Plans','fk_Patient','Dim_Patients','pk_Patient',1),
 ('Fact_Treatment_Plans','fk_Practice_Site','Dim_Practice_Sites','pk_Practice_Site',1),
 ('Fact_Treatment_Plans','fk_Practitioner','Dim_Practitioners','pk_Practitioner',1),
 ('Fact_Treatment_Plans','fk_Treatment_Plan','Dim_Treatment_Plans','pk_Treatment_Plan',1);
GO
