-- =============================================================================
-- Audit.Process_Config  — seed data
-- =============================================================================
-- Idempotent: deletes all rows and re-inserts from source.
-- Run after tables are created (group 2) and before procedures (group 3).
-- =============================================================================

DELETE FROM Audit.Process_Config;
GO

-- (GOLD_LOAD_ALL removed 2026-06-21: orchestrators are not DAG jobs; Gold.usp_Load_All
--  doesn't exist -- the Silver+Gold orchestrator is Audit.usp_Load_All.)

-- ── GOLD dimensions ───────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_ACCOUNTS',        'Gold.usp_Load_Dim_Accounts',        'Load Gold.Dim_Accounts from Silver layer',        '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_ACQUISITION_SOURCES', 'Gold.usp_Load_Dim_Acquisition_Sources', 'Load Gold.Dim_Acquisition_Sources from Silver layer', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_DATE',            'Gold.usp_Load_Dim_Date',            'Load Gold.Dim_Date from calculated values',       '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_DATE_GROUPING',   'Gold.usp_Load_Dim_Date_Grouping',   'Load Gold.Dim_Date_Grouping — named date-range bands with prior-year keys', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PATIENTS',        'Gold.usp_Load_Dim_Patients',        'Load Gold.Dim_Patients from Silver layer',        '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PAYMENT_PLANS',   'Gold.usp_Load_Dim_Payment_Plans',   'Load Gold.Dim_Payment_Plans from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PRACTICE_SITES',  'Gold.usp_Load_Dim_Practice_Sites',  'Load Gold.Dim_Practice_Sites from Silver layer',  '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PRACTITIONERS',   'Gold.usp_Load_Dim_Practitioners',   'Load Gold.Dim_Practitioners from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_CANCELLATION_REASONS', 'Gold.usp_Load_Dim_Cancellation_Reasons', 'Load Gold.Dim_Cancellation_Reasons from Silver layer', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_TREATMENT_PLANS',     'Gold.usp_Load_Dim_Treatment_Plans',     'Load Gold.Dim_Treatment_Plans from Silver layer',     '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_TREATMENTS',      'Gold.usp_Load_Dim_Treatments',      'Load Gold.Dim_Treatments from Silver layer',      '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_USERS',           'Gold.usp_Load_Dim_Users',           'Load Gold.Dim_Users from Silver layer',           '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_NHS_CONTRACTS',   'Gold.usp_Load_Dim_NHS_Contracts',   'Load Gold.Dim_NHS_Contracts from Silver.Contracts',  '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_INVOICES',        'Gold.usp_Load_Dim_Invoices',        'Load Gold.Dim_Invoices (invoice header dimension) from Silver.Invoices', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');

-- ── GOLD aggregates ──────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_DAILY',       'Gold.usp_Load_Aggregate_Site_Patient_Practitioner_Daily', 'Rebuild Gold.Aggregate_Site_Patient_Practitioner_Daily from Gold fact/dim tables', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_SITE_PATIENT','Gold.usp_Load_Aggregate_Site_Patient_Current',            'Rebuild Gold.Aggregate_Site_Patient_Current — current patient status per site',    '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_SITE_PRACT',  'Gold.usp_Load_Aggregate_Site_Practitioner_Current',       'Rebuild Gold.Aggregate_Site_Practitioner_Current — diary availability per practitioner', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_PRACT_CONTRIBUTION', 'Gold.usp_Load_Aggregate_Practitioner_Contribution', 'Rebuild Gold.Aggregate_Practitioner_Contribution — production/associate-pay/contribution per practitioner. GOLD_AGG: reads Gold.Fact_Invoice_Items + Input.Practitioner_Pay.', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
-- Post-fact derived load (AGG category so the dependency generator orders it after Gold.Fact_Appointments).
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_APPOINTMENT_JOURNEY', 'Gold.usp_Load_Fact_Appointment_Journey', 'Full rebuild of Gold.Fact_Appointment_Journey (per-mode next-appointment pointers) from Gold.Fact_Appointments — source for the Patient Journeys Alluvial', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
-- Per-FY metric actuals (target generation + target-vs-actual cards). AGG: reads Gold.Fact_Invoice_Items + the daily aggregate, so the Gold->Agg rule orders it after them.
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_METRIC_ACTUALS', 'Gold.usp_Load_Fact_Metric_Actuals', 'Materialise per-FY metric actuals (Tier-1: total/nhs/private revenue, new_patients) at global/site/practitioner grain from Gold.Fact_Invoice_Items + Gold.Aggregate_Site_Patient_Practitioner_Daily — source for target generation and target-vs-actual cards', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');

-- ── GOLD facts ────────────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_DAILY_TARGETS',           'Gold.usp_Load_Fact_Daily_Targets',          'Explode cumulative targets from Input.Targets into one row per working day per FY. GOLD_AGG: reads Gold.Fact_Contracts, so the Gold->Agg rule orders it after that fact. Table name Fact_Daily_Targets retained.', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_TARGETS',                'Gold.usp_Load_Fact_Targets',                'Sync Input.Targets to Gold.Fact_Targets — must run before Fact_Effective_Targets',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_EFFECTIVE_TARGETS',       'Gold.usp_Load_Fact_Effective_Targets',      'Pre-resolve site vs practice target precedence into Gold.Fact_Effective_Targets. GOLD_AGG: reads Gold.Fact_Targets, so the Gold->Agg rule orders it after that fact. Table name Fact_Effective_Targets retained.', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_KPI_SNAPSHOT',            'Gold.usp_Load_Fact_KPI_Snapshot',           'Point-in-time KPI snapshots (weekly + monthly) — treatment pipeline value + future metrics. Categorised GOLD_AGG: a snapshot/aggregate that reads Gold facts (e.g. Fact_Recalls), so the Gold->Agg dependency rule orders it after them. Table name Fact_KPI_Snapshot retained.', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_APPOINTMENTS',           'Gold.usp_Load_Fact_Appointments',           'Load Gold.Fact_Appointments from Silver layer',           '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_CONTRACTS',              'Gold.usp_Load_Fact_Contracts',              'Load Gold.Fact_Contracts from Silver layer',              '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_NHS_CLAIMS',             'Gold.usp_Load_Fact_NHS_Claims',             'Load Gold.Fact_NHS_Claims from Silver.NHS_Claims',                             '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_NHS_CONTRACT_WEEK',      'Gold.usp_Load_Fact_NHS_Contract_Week',      'Load Gold.Fact_NHS_Contract_Week — weekly pro-rated UDA targets per contract', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_INVOICE_ITEMS',          'Gold.usp_Load_Fact_Invoice_Items',          'Load Gold.Fact_Invoice_Items (invoice-line grain) from Silver layer', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_INVOICES',               'Gold.usp_Load_Fact_Invoices',               'Load Gold.Fact_Invoices (invoice grain) from Silver.Invoices', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_PAYMENTS',               'Gold.usp_Load_Fact_Payments',               'Load Gold.Fact_Payments from Silver layer — deposit detection via incomplete treatment plan allocations', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_PRACTITIONER_DIARIES',   'Gold.usp_Load_Fact_Practitioner_Diaries',   'Load Gold.Fact_Practitioner_Diaries from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_RECALLS',                'Gold.usp_Load_Fact_Recalls',                'Load Gold.Fact_Recalls from Silver layer',                '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_TREATMENT_APPOINTMENTS', 'Gold.usp_Load_Fact_Treatment_Appointments', 'Load Gold.Fact_Treatment_Appointments from Silver layer', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_TREATMENT_PLAN_ITEMS',   'Gold.usp_Load_Fact_Treatment_Plan_Items',   'Load Gold.Fact_Treatment_Plan_Items from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_TREATMENT_PLANS',        'Gold.usp_Load_Fact_Treatment_Plans',        'Load Gold.Fact_Treatment_Plans (plan grain) from Silver.Treatment_Plans', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');

-- ── SILVER ────────────────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_ACCOUNTS',                  'Silver.usp_Load_Accounts',                  'Load Silver.Accounts from Bronze.Accounts using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_ACQUISITION_SOURCES',               'Silver.usp_Load_Acquisition_Sources',               'Load Silver.Acquisition_Sources from Bronze.Acquisition_Sources using MERGE upsert',               '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_APPOINTMENT_CANCELLATION_REASONS',  'Silver.usp_Load_Appointment_Cancellation_Reasons',  'Load Silver.Appointment_Cancellation_Reasons from Bronze.Cancellation_Reasons using MERGE upsert', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_APPOINTMENTS',              'Silver.usp_Load_Appointments',              'Load Silver.Appointments from Bronze.Appointments using MERGE upsert',                          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_CONTRACTS',                 'Silver.usp_Load_Contracts',                 'Load Silver.Contracts from Bronze.Contracts using MERGE upsert',                                '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_FEES',                      'Silver.usp_Load_Fees',                      'Load Silver.Fees from Bronze.Fees using MERGE upsert',                                          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_INVOICE_ITEMS',             'Silver.usp_Load_Invoice_Items',             'Load Silver.Invoice_Items from Bronze.Invoice_Items using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_INVOICES',                  'Silver.usp_Load_Invoices',                  'Load Silver.Invoices from Bronze.Invoices using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_NHS_CLAIMS',                'Silver.usp_Load_NHS_Claims',                'Load Silver.NHS_Claims from Bronze.NHS_Claims using MERGE upsert',                              '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PATIENT_REFERRALS',         'Silver.usp_Load_Patient_Referrals',         'Load Silver.Patient_Referrals from Bronze.Patient_Referrals using upsert',                      '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PATIENT_STATS',             'Silver.usp_Load_Patient_Stats',             'Load Silver.Patient_Stats from Bronze.Patient_Stats using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PATIENTS',                  'Silver.usp_Load_Patients',                  'Load Silver.Patients from Bronze.Patients using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENT_ALLOCATIONS',       'Silver.usp_Load_Payment_Allocations',       'Load Silver.Payment_Allocations from Bronze.Payment_Allocations using MERGE upsert',            '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENT_EXPLANATIONS',      'Silver.usp_Load_Payment_Explanations',      'Load Silver.Payment_Explanations from Bronze.Payment_Explanations using MERGE upsert',          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENT_PLANS',             'Silver.usp_Load_Payment_Plans',             'Load Silver.Payment_Plans from Bronze.Payment_Plans using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENTS',                  'Silver.usp_Load_Payments',                  'Load Silver.Payments from Bronze.Payments using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTICE',                  'Silver.usp_Load_Practice',                  'Load Silver.Practice from Bronze.Practice using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONER_DIARY',        'Silver.usp_Load_Practitioner_Diary',        'Load Silver.Practitioner_Diary from Bronze.Practitioner_Diary using MERGE upsert',              '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONER_DIARY_BREAKS', 'Silver.usp_Load_Practitioner_Diary_Breaks', 'Load Silver.Practitioner_Diary_Breaks from Bronze.Practitioner_Diary_Breaks using MERGE upsert', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONERS',                        'Silver.usp_Load_Practitioners',                        'Load Silver.Practitioners from Bronze.Practitioners using MERGE upsert',                                          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONER_CONTRACT_TARGETS', 'Silver.usp_Load_Practitioner_Contract_Targets', 'Parse contract_targets JSON from Bronze.Practitioners into Silver.Practitioner_Contract_Targets', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_RECALLS',                   'Silver.usp_Load_Recalls',                   'Load Silver.Recalls from Bronze.Recalls using MERGE upsert',                                    '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_SITES',                     'Silver.usp_Load_Sites',                     'Load Silver.Sites from Bronze.Sites using MERGE upsert',                                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_SUNDRIES',                  'Silver.usp_Load_Sundries',                  'Load Silver.Sundries from Bronze.Sundries using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_APPOINTMENTS',    'Silver.usp_Load_Treatment_Appointments',    'Load Silver.Treatment_Appointments from Bronze.Treatment_Appointments using MERGE upsert',      '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_CATEGORIES',      'Silver.usp_Load_Treatment_Categories',      'Load Silver.Treatment_Categories from Bronze.Treatment_Categories using MERGE upsert',          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_PLAN_ITEMS',      'Silver.usp_Load_Treatment_Plan_Items',      'Load Silver.Treatment_Plan_Items from Bronze.Treatment_Plan_Items using MERGE upsert',          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_PLANS',           'Silver.usp_Load_Treatment_Plans',           'Load Silver.Treatment_Plans from Bronze.Treatment_Plans using MERGE upsert',                    '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENTS',                'Silver.usp_Load_Treatments',                'Load Silver.Treatments from Bronze.Treatments using MERGE upsert',                              '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_USERS',                     'Silver.usp_Load_Users',                     'Load Silver.Users from Bronze.Users using MERGE upsert',                                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');

-- == BRONZE -- one job per table. Tenant is supplied at
--    runtime by Orchestrate_Build via Audit.ETL_Run_Process, which resolves the
--    {TID} token below. Execution stays per-tenant (one extract per tenant);
--    Process_Execution_Log records the resolved @Tenant_ID per run.
--    Process_Code pattern: BRONZE_{ENTITY_UPPER}

INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PRACTICE', 'Bronze.usp_Load_Practice', 'Bronze: Practice (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_SITES', 'Bronze.usp_Load_Sites', 'Bronze: Sites (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_USERS', 'Bronze.usp_Load_Users', 'Bronze: Users (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PRACTITIONERS', 'Bronze.usp_Load_Practitioners', 'Bronze: Practitioners (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PAYMENT_PLANS', 'Bronze.usp_Load_Payment_Plans', 'Bronze: Payment_Plans (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_TREATMENTS', 'Bronze.usp_Load_Treatments', 'Bronze: Treatments (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_TREATMENT_CATEGORIES', 'Bronze.usp_Load_Treatment_Categories', 'Bronze: Treatment_Categories (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_ACQUISITION_SOURCES', 'Bronze.usp_Load_Acquisition_Sources', 'Bronze: Acquisition_Sources (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_CANCELLATION_REASONS', 'Bronze.usp_Load_Cancellation_Reasons', 'Bronze: Cancellation_Reasons (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_WAITING_LISTS', 'Bronze.usp_Load_Waiting_Lists', 'Bronze: Waiting_Lists (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_SUNDRIES', 'Bronze.usp_Load_Sundries', 'Bronze: Sundries (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_CONTRACTS', 'Bronze.usp_Load_Contracts', 'Bronze: Contracts (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_FEES', 'Bronze.usp_Load_Fees', 'Bronze: Fees (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PRACTITIONER_DIARY_BREAKS', 'Bronze.usp_Load_Practitioner_Diary_Breaks', 'Bronze: Practitioner_Diary_Breaks (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PATIENTS', 'Bronze.usp_Load_Patients', 'Bronze: Patients (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_ACCOUNTS', 'Bronze.usp_Load_Accounts', 'Bronze: Accounts (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_APPOINTMENTS', 'Bronze.usp_Load_Appointments', 'Bronze: Appointments (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_INVOICES', 'Bronze.usp_Load_Invoices', 'Bronze: Invoices (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_INVOICE_ITEMS', 'Bronze.usp_Load_Invoice_Items', 'Bronze: Invoice_Items (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PAYMENTS', 'Bronze.usp_Load_Payments', 'Bronze: Payments (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_TREATMENT_PLANS', 'Bronze.usp_Load_Treatment_Plans', 'Bronze: Treatment_Plans (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_TREATMENT_PLAN_ITEMS', 'Bronze.usp_Load_Treatment_Plan_Items', 'Bronze: Treatment_Plan_Items (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_RECALLS', 'Bronze.usp_Load_Recalls', 'Bronze: Recalls (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PRACTITIONER_DIARY_ENTRIES', 'Bronze.usp_Load_Practitioner_Diary_Entries', 'Bronze: Practitioner_Diary_Entries (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_NHS_CLAIMS', 'Bronze.usp_Load_NHS_Claims', 'Bronze: NHS_Claims (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PATIENT_STATS', 'Bronze.usp_Load_Patient_Stats', 'Bronze: Patient_Stats (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PAYMENT_ALLOCATIONS', 'Bronze.usp_Load_Payment_Allocations', 'Bronze: Payment_Allocations (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PAYMENT_EXPLANATIONS', 'Bronze.usp_Load_Payment_Explanations', 'Bronze: Payment_Explanations (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_TREATMENT_APPOINTMENTS', 'Bronze.usp_Load_Treatment_Appointments', 'Bronze: Treatment_Appointments (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_PATIENT_REFERRALS', 'Bronze.usp_Load_Patient_Referrals', 'Bronze: Patient_Referrals (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_ROOMS', 'Bronze.usp_Load_Rooms', 'Bronze: Rooms (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');

INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_XERO_ACCOUNTS', 'Bronze.usp_Load_Xero_Accounts', 'Bronze: Xero_Accounts (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_XERO_LINES', 'Bronze.usp_Load_Xero_Lines', 'Bronze: Xero_Lines (all tenants; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_XERO_ORGS', 'Bronze.usp_Load_Xero_Orgs', 'Bronze: Xero_Orgs (org -> Tenant_ID + default site; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('BRONZE_XERO_TRACKING', 'Bronze.usp_Load_Xero_Tracking', 'Bronze: Xero_Tracking (categories + options; runtime @Tenant_ID/@Full_Refresh)', '@Tenant_ID = {TID}', 'BRONZE', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_XERO_ACCOUNTS', 'Silver.usp_Load_Xero_Accounts', 'Load Silver.Xero_Accounts (chart + PL_Group) from Bronze.Xero_Accounts', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_XERO_ORGS', 'Silver.usp_Load_Xero_Orgs', 'Load Silver.Xero_Orgs (org registry) from Bronze.Xero_Orgs', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_XERO_TRACKING', 'Silver.usp_Load_Xero_Tracking', 'Load Silver.Xero_Tracking (tracking reference) from Bronze.Xero_Tracking', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_XERO_FINANCE_LINES', 'Silver.usp_Load_Xero_Finance_Lines', 'Load Silver.Xero_Finance_Lines (P&L transform) from Bronze.Xero_Lines + Silver.Xero_Accounts + Silver.Xero_Orgs', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_GL_ACCOUNT', 'Gold.usp_Load_Dim_GL_Account', 'Load Gold.Dim_GL_Account from Silver.Xero_Accounts', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_FINANCE', 'Gold.usp_Load_Fact_Finance', 'Load Gold.Fact_Finance (P&L line grain) from Silver.Xero_Finance_Lines', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');

-- == POST-RUN GATE -- referential-integrity + sentinel check. NOT a DAG job: category
--    POSTRUN_GATE keeps it OUT of the dependency waves (Orchestrate_Build CELL 4) so it
--    runs AFTER every load (CELL 9b). THROWs on any orphaned fact fk / missing dim -1
--    sentinel -> ETL_Run_Process logs FAILED -> the build skips the model refresh.
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('POSTRUN_RI_CHECK', 'Audit.usp_Check_Referential_Integrity', 'Post-run referential-integrity + sentinel gate. Runs AFTER all loads (NOT in the DAG -- category POSTRUN_GATE excludes it from the waves). THROWs on any orphaned fact fk or missing dim -1 sentinel so ETL_Run_Process logs FAILED and the build skips the semantic-model refresh. See Audit.RI_Check_Result.', '@Mode = ''LIVE'', @Logging = 1', 'POSTRUN_GATE', 'PROCEDURE');
