-- =============================================================================
-- Audit.Process_Config  — seed data
-- =============================================================================
-- Idempotent: deletes all rows and re-inserts from source.
-- Run after tables are created (group 2) and before procedures (group 3).
-- =============================================================================

DELETE FROM Audit.Process_Config;
GO

-- ── GOLD orchestrator ─────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_LOAD_ALL', 'Gold.usp_Load_All', 'Orchestrates full Gold layer load - all dimensions then all facts', '@Mode = ''LIVE'', @Logging = 1', 'GOLD', 'PROCEDURE');

-- ── GOLD dimensions ───────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_ACCOUNTS',        'Gold.usp_Load_Dim_Accounts',        'Load Gold.Dim_Accounts from Silver layer',        '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_DATE',            'Gold.usp_Load_Dim_Date',            'Load Gold.Dim_Date from calculated values',       '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_DATE_GROUPING',   'Gold.usp_Load_Dim_Date_Grouping',   'Load Gold.Dim_Date_Grouping — named date-range bands with prior-year keys', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PATIENTS',        'Gold.usp_Load_Dim_Patients',        'Load Gold.Dim_Patients from Silver layer',        '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PAYMENT_PLANS',   'Gold.usp_Load_Dim_Payment_Plans',   'Load Gold.Dim_Payment_Plans from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PRACTICE_SITES',  'Gold.usp_Load_Dim_Practice_Sites',  'Load Gold.Dim_Practice_Sites from Silver layer',  '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_PRACTITIONERS',   'Gold.usp_Load_Dim_Practitioners',   'Load Gold.Dim_Practitioners from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_TREATMENT_PLANS', 'Gold.usp_Load_Dim_Treatment_Plans', 'Load Gold.Dim_Treatment_Plans from Silver layer', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_TREATMENTS',      'Gold.usp_Load_Dim_Treatments',      'Load Gold.Dim_Treatments from Silver layer',      '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_DIM_USERS',           'Gold.usp_Load_Dim_Users',           'Load Gold.Dim_Users from Silver layer',           '@Mode = ''LIVE'', @Logging = 1', 'GOLD_DIM', 'PROCEDURE');

-- ── GOLD aggregates ──────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_DAILY',       'Gold.usp_Load_Aggregate_Site_Patient_Practitioner_Daily', 'Rebuild Gold.Aggregate_Site_Patient_Practitioner_Daily from Gold fact/dim tables', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_SITE_PATIENT','Gold.usp_Load_Aggregate_Site_Patient_Current',            'Rebuild Gold.Aggregate_Site_Patient_Current — current patient status per site',    '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_AGG_SITE_PRACT',  'Gold.usp_Load_Aggregate_Site_Practitioner_Current',       'Rebuild Gold.Aggregate_Site_Practitioner_Current — diary availability per practitioner', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_AGG', 'PROCEDURE');

-- ── GOLD facts ────────────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_APPOINTMENTS',           'Gold.usp_Load_Fact_Appointments',           'Load Gold.Fact_Appointments from Silver layer',           '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_CONTRACTS',              'Gold.usp_Load_Fact_Contracts',              'Load Gold.Fact_Contracts from Silver layer',              '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_INVOICE_ITEMS',          'Gold.usp_Load_Fact_Invoice_Items',          'Load Gold.Fact_Invoice_Items from Silver layer',          '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_PRACTITIONER_DIARIES',   'Gold.usp_Load_Fact_Practitioner_Diaries',   'Load Gold.Fact_Practitioner_Diaries from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_RECALLS',                'Gold.usp_Load_Fact_Recalls',                'Load Gold.Fact_Recalls from Silver layer',                '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_TREATMENT_APPOINTMENTS', 'Gold.usp_Load_Fact_Treatment_Appointments', 'Load Gold.Fact_Treatment_Appointments from Silver layer', '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('GOLD_FACT_TREATMENT_PLAN_ITEMS',   'Gold.usp_Load_Fact_Treatment_Plan_Items',   'Load Gold.Fact_Treatment_Plan_Items from Silver layer',   '@Mode = ''LIVE'', @Logging = 1', 'GOLD_FACT', 'PROCEDURE');

-- ── SILVER ────────────────────────────────────────────────────────────────────
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_ACCOUNTS',                  'Silver.usp_Load_Accounts',                  'Load Silver.Accounts from Bronze.Accounts using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_ACQUISITION_SOURCES',       'Silver.usp_Load_Acquisition_Sources',       'Load Silver.Acquisition_Sources from Bronze.Acquisition_Sources using MERGE upsert',           '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_APPOINTMENTS',              'Silver.usp_Load_Appointments',              'Load Silver.Appointments from Bronze.Appointments using MERGE upsert',                          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_CONTRACTS',                 'Silver.usp_Load_Contracts',                 'Load Silver.Contracts from Bronze.Contracts using MERGE upsert',                                '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_FEES',                      'Silver.usp_Load_Fees',                      'Load Silver.Fees from Bronze.Fees using MERGE upsert',                                          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_INVOICE_ITEMS',             'Silver.usp_Load_Invoice_Items',             'Load Silver.Invoice_Items from Bronze.Invoice_Items using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_INVOICES',                  'Silver.usp_Load_Invoices',                  'Load Silver.Invoices from Bronze.Invoices using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_NHS_CLAIMS',                'Silver.usp_Load_NHS_Claims',                'Load Silver.Nhs_Claims from Bronze.Nhs_Claims using MERGE upsert',                              '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PATIENT_STATS',             'Silver.usp_Load_Patient_Stats',             'Load Silver.Patient_Stats from Bronze.Patient_Stats using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PATIENTS',                  'Silver.usp_Load_Patients',                  'Load Silver.Patients from Bronze.Patients using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENT_ALLOCATIONS',       'Silver.usp_Load_Payment_Allocations',       'Load Silver.Payment_Allocations from Bronze.Payment_Allocations using MERGE upsert',            '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENT_EXPLANATIONS',      'Silver.usp_Load_Payment_Explanations',      'Load Silver.Payment_Explanations from Bronze.Payment_Explanations using MERGE upsert',          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENT_PLANS',             'Silver.usp_Load_Payment_Plans',             'Load Silver.Payment_Plans from Bronze.Payment_Plans using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PAYMENTS',                  'Silver.usp_Load_Payments',                  'Load Silver.Payments from Bronze.Payments using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTICE',                  'Silver.usp_Load_Practice',                  'Load Silver.Practice from Bronze.Practice using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONER_DIARY',        'Silver.usp_Load_Practitioner_Diary',        'Load Silver.Practitioner_Diary from Bronze.Practitioner_Diary using MERGE upsert',              '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONER_DIARY_BREAKS', 'Silver.usp_Load_Practitioner_Diary_Breaks', 'Load Silver.Practitioner_Diary_Breaks from Bronze.Practitioner_Diary_Breaks using MERGE upsert', '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_PRACTITIONERS',             'Silver.usp_Load_Practitioners',             'Load Silver.Practitioners from Bronze.Practitioners using MERGE upsert',                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_RECALLS',                   'Silver.usp_Load_Recalls',                   'Load Silver.Recalls from Bronze.Recalls using MERGE upsert',                                    '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_SITES',                     'Silver.usp_Load_Sites',                     'Load Silver.Sites from Bronze.Sites using MERGE upsert',                                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_SUNDRIES',                  'Silver.usp_Load_Sundries',                  'Load Silver.Sundries from Bronze.Sundries using MERGE upsert',                                  '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_APPOINTMENTS',    'Silver.usp_Load_Treatment_Appointments',    'Load Silver.Treatment_Appointments from Bronze.Treatment_Appointments using MERGE upsert',      '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_CATEGORIES',      'Silver.usp_Load_Treatment_Categories',      'Load Silver.Treatment_Categories from Bronze.Treatment_Categories using MERGE upsert',          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_PLAN_ITEMS',      'Silver.usp_Load_Treatment_Plan_Items',      'Load Silver.Treatment_Plan_Items from Bronze.Treatment_Plan_Items using MERGE upsert',          '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENT_PLANS',           'Silver.usp_Load_Treatment_Plans',           'Load Silver.Treatment_Plans from Bronze.Treatment_Plans using MERGE upsert',                    '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_TREATMENTS',                'Silver.usp_Load_Treatments',                'Load Silver.Treatments from Bronze.Treatments using MERGE upsert',                              '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');
INSERT INTO Audit.Process_Config (Process_Code, Process_Name, Process_Desc, Process_Parameters, Process_Category_Code, Process_Type_Code) VALUES ('SILVER_USERS',                     'Silver.usp_Load_Users',                     'Load Silver.Users from Bronze.Users using MERGE upsert',                                        '@Mode = ''LIVE'', @Logging = 1', 'SILVER', 'PROCEDURE');

GO
