/****** Object:  Table [Gold].[Dim_Patients]    Script Date: 20/04/2026 10:15:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS [Gold].[Dim_Patients]
GO
CREATE TABLE [Gold].[Dim_Patients](
	[pk_Patient] [bigint] NOT NULL,
	[Tenant_ID] [int] NOT NULL,
	[Patient_ID] [int] NOT NULL,
	[Account_ID] [int] NULL,
	[Title] [VARCHAR](20) NULL,
	[First_Name] [VARCHAR](100) NULL,
	[Middle_Name] [VARCHAR](100) NULL,
	[Last_Name] [VARCHAR](100) NULL,
	[Preferred_Name] [VARCHAR](100) NULL,
	[Full_Name] [VARCHAR](255) NULL,
	[Date_Of_Birth] [date] NULL,
	[Age_Years] [int] NULL,
	[Gender_Code] [int] NULL,
	[Gender_Description] [VARCHAR](20) NULL,
	[Ethnicity_Code] [int] NULL,
	[NHS_Number] [VARCHAR](20) NULL,
	[NI_Number] [VARCHAR](20) NULL,
	[Email_Address] [VARCHAR](255) NULL,
	[Home_Phone] [VARCHAR](50) NULL,
	[Mobile_Phone] [VARCHAR](50) NULL,
	[Work_Phone] [VARCHAR](50) NULL,
	[Address_Line_1] [VARCHAR](255) NULL,
	[Address_Line_2] [VARCHAR](255) NULL,
	[Town] [VARCHAR](100) NULL,
	[County] [VARCHAR](100) NULL,
	[Postcode] [VARCHAR](20) NULL,
	[Active] [bit] NULL,
	[Medical_Alert] [bit] NULL,
	[Medical_Alert_Text] [VARCHAR](255) NULL,
	[Payment_Plan_ID] [int] NULL,
	[Site_ID] [VARCHAR](50) NULL,
	[Family_ID] [VARCHAR](255) NULL,
	[Acquisition_Source_ID] [VARCHAR](50) NULL,
	[Dentist_Practitioner_ID] [int] NULL,
	[Hygienist_Practitioner_ID] [int] NULL,
	[Dentist_Recall_Date] [date] NULL,
	[Dentist_Recall_Interval_Months] [int] NULL,
	[Hygienist_Recall_Date] [date] NULL,
	[Hygienist_Recall_Interval_Months] [int] NULL,
	[Recall_Method] [VARCHAR](100) NULL,
	[Preferred_Contact_Method] [VARCHAR](50) NULL,
	[Use_Email] [bit] NULL,
	[Use_SMS] [bit] NULL,
	[Marketing_Consent] [VARCHAR](255) NULL,
	[Occupation] [VARCHAR](255) NULL,
	[Legacy_ID] [VARCHAR](255) NULL,
	[Custom_Field_1] [VARCHAR](255) NULL,
	[Custom_Field_2] [VARCHAR](255) NULL,
	[First_Appointment_Date] [date] NULL,
	[Last_Appointment_Date] [date] NULL,
	[Next_Appointment_Date] [date] NULL,
	[First_Exam_Date] [date] NULL,
	[Last_Exam_Date] [date] NULL,
	[Next_Exam_Date] [date] NULL,
	[Last_Scale_Polish_Date] [date] NULL,
	[Next_Scale_Polish_Date] [date] NULL,
	[Last_FTA_Date] [date] NULL,
	[Last_Cancelled_Appointment_Date] [date] NULL,
	[Total_Paid] [decimal](18, 4) NULL,
	[Total_Invoiced] [decimal](18, 4) NULL,
	[NHS_Exemption_Code] [int] NULL,
	[Patient_Created_Date] [date] NULL,
	[Patient_Updated_Date] [date] NULL,
	[Patient_Count] [int] NOT NULL,
	[DW_Created_At] [datetime2](6) NOT NULL,
	[DW_Updated_At] [datetime2](6) NOT NULL
)
GO
