-- =============================================================================
-- Gold.Fact_Patient_Journeys — seed data
-- =============================================================================
-- Fake patient journey flow data for Sankey / Alluvial diagram prototype.
-- 104 rows: unique path combinations across 5 stages.
--   Channel > Current_Appointment > Next_Outcome > Next_Appointment > Current_State
-- =============================================================================

DELETE FROM Gold.Fact_Patient_Journeys;
GO

INSERT INTO Gold.Fact_Patient_Journeys
    (pk_patient_journey, Channel, Current_Appointment, Next_Outcome,
     Next_Appointment, Current_State, Patient_Count)
VALUES
    (1, 'New', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 157),
    (2, 'New', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 13),
    (3, 'New', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 8),
    (4, 'New', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'No longer a Patient', 3),
    (5, 'New', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 52),
    (6, 'New', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 4),
    (7, 'New', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 2),
    (8, 'New', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'No longer a Patient', 1),
    (9, 'New', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Exam Scheduled', 35),
    (10, 'New', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Uncertain', 3),
    (11, 'New', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Requiring Contact', 2),
    (12, 'New', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'No longer a Patient', 1),
    (13, 'New', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Exam Scheduled', 21),
    (14, 'New', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Uncertain', 2),
    (15, 'New', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Requiring Contact', 1),
    (16, 'New', 'Exam (Current)', 'Closed', 'None', 'No longer a Patient', 16),
    (17, 'BBYL', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 470),
    (18, 'BBYL', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 39),
    (19, 'BBYL', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 23),
    (20, 'BBYL', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'No longer a Patient', 8),
    (21, 'BBYL', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 157),
    (22, 'BBYL', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 13),
    (23, 'BBYL', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 7),
    (24, 'BBYL', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'No longer a Patient', 3),
    (25, 'BBYL', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Exam Scheduled', 104),
    (26, 'BBYL', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Uncertain', 9),
    (27, 'BBYL', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Requiring Contact', 5),
    (28, 'BBYL', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'No longer a Patient', 2),
    (29, 'BBYL', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Exam Scheduled', 63),
    (30, 'BBYL', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Uncertain', 5),
    (31, 'BBYL', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Requiring Contact', 3),
    (32, 'BBYL', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'No longer a Patient', 1),
    (33, 'BBYL', 'Exam (Current)', 'Closed', 'None', 'No longer a Patient', 48),
    (34, 'BBYL', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 83),
    (35, 'BBYL', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 7),
    (36, 'BBYL', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 4),
    (37, 'BBYL', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'No longer a Patient', 1),
    (38, 'BBYL', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 125),
    (39, 'BBYL', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 11),
    (40, 'BBYL', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 5),
    (41, 'BBYL', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'No longer a Patient', 3),
    (42, 'Online Booking', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 78),
    (43, 'Online Booking', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 7),
    (44, 'Online Booking', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 4),
    (45, 'Online Booking', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'No longer a Patient', 1),
    (46, 'Online Booking', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 26),
    (47, 'Online Booking', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 2),
    (48, 'Online Booking', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 1),
    (49, 'Online Booking', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'No longer a Patient', 1),
    (50, 'Online Booking', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Exam Scheduled', 17),
    (51, 'Online Booking', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Uncertain', 1),
    (52, 'Online Booking', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Requiring Contact', 1),
    (53, 'Online Booking', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Exam Scheduled', 10),
    (54, 'Online Booking', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Uncertain', 1),
    (55, 'Online Booking', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Requiring Contact', 1),
    (56, 'Online Booking', 'Exam (Current)', 'Closed', 'None', 'No longer a Patient', 8),
    (57, 'Online Booking', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 14),
    (58, 'Online Booking', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 1),
    (59, 'Online Booking', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 1),
    (60, 'Online Booking', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 21),
    (61, 'Online Booking', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 2),
    (62, 'Online Booking', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 1),
    (63, 'Emergency', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 20),
    (64, 'Emergency', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 2),
    (65, 'Emergency', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 1),
    (66, 'Emergency', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 7),
    (67, 'Emergency', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 1),
    (68, 'Emergency', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Exam Scheduled', 4),
    (69, 'Emergency', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Exam Scheduled', 3),
    (70, 'Emergency', 'Exam (Current)', 'Closed', 'None', 'No longer a Patient', 2),
    (71, 'Emergency', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 28),
    (72, 'Emergency', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 2),
    (73, 'Emergency', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 1),
    (74, 'Emergency', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 42),
    (75, 'Emergency', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 4),
    (76, 'Emergency', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 2),
    (77, 'Emergency', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'No longer a Patient', 1),
    (78, 'Referral', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 39),
    (79, 'Referral', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 3),
    (80, 'Referral', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 2),
    (81, 'Referral', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'No longer a Patient', 1),
    (82, 'Referral', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 13),
    (83, 'Referral', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 1),
    (84, 'Referral', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Requiring Contact', 1),
    (85, 'Referral', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Exam Scheduled', 9),
    (86, 'Referral', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Uncertain', 1),
    (87, 'Referral', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Exam Scheduled', 5),
    (88, 'Referral', 'Exam (Current)', 'Closed', 'None', 'No longer a Patient', 4),
    (89, 'Referral', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 7),
    (90, 'Referral', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 1),
    (91, 'Referral', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 10),
    (92, 'Referral', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 1),
    (93, 'Other', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 20),
    (94, 'Other', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 2),
    (95, 'Other', 'Exam (Current)', 'BBYL Exam', 'Exam (Next)', 'Requiring Contact', 1),
    (96, 'Other', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 7),
    (97, 'Other', 'Exam (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 1),
    (98, 'Other', 'Exam (Current)', 'Awaiting Recall', 'Exam (Next)', 'Exam Scheduled', 4),
    (99, 'Other', 'Exam (Current)', 'Recall Sent', 'Exam (Next)', 'Exam Scheduled', 3),
    (100, 'Other', 'Exam (Current)', 'Closed', 'None', 'No longer a Patient', 2),
    (101, 'Other', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Exam Scheduled', 7),
    (102, 'Other', 'Treatment (Current)', 'BBYL Exam', 'Exam (Next)', 'Uncertain', 1),
    (103, 'Other', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Treatment Scheduled', 10),
    (104, 'Other', 'Treatment (Current)', 'BBYL Treatment', 'Treatment (Next)', 'Uncertain', 1);
GO