/****** Object:  Table [Silver].[Patients]    Script Date: 20/04/2026 10:15:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS [Silver].[Patients]
GO
CREATE TABLE [Silver].[Patients](
	[Patient_Id] [int] NOT NULL,
	[Account_Id] [int] NULL,
	[Site_Id] [VARCHAR](50) NULL,
	[Active] [bit] NULL,
	[Title] [VARCHAR](20) NULL,
	[First_Name] [VARCHAR](100) NULL,
	[Middle_Name] [VARCHAR](100) NULL,
	[Last_Name] [VARCHAR](100) NULL,
	[Preferred_Name] [VARCHAR](100) NULL,
	[Preferred_Phone_Number] [VARCHAR](100) NULL,
	[Date_Of_Birth] [date] NULL,
	[Gender] [VARCHAR](20) NULL,
	[Ethnicity] [VARCHAR](50) NULL,
	[NHS_Number] [VARCHAR](20) NULL,
	[NI_Number] [VARCHAR](20) NULL,
	[PPS_Number] [VARCHAR](20) NULL,
	[Email_Address] [VARCHAR](255) NULL,
	[Mobile_Phone] [VARCHAR](50) NULL,
	[Mobile_Phone_Country] [VARCHAR](50) NULL,
	[Home_Phone] [VARCHAR](50) NULL,
	[Home_Phone_Country] [VARCHAR](50) NULL,
	[Work_Phone] [VARCHAR](50) NULL,
	[Work_Phone_Country] [VARCHAR](50) NULL,
	[Address_Line_1] [VARCHAR](255) NULL,
	[Address_Line_2] [VARCHAR](255) NULL,
	[Town] [VARCHAR](100) NULL,
	[County] [VARCHAR](100) NULL,
	[Postcode] [VARCHAR](20) NULL,
	[Custom_Field_1] [VARCHAR](100) NULL,
	[Custom_Field_2] [VARCHAR](100) NULL,
	[Status] [VARCHAR](50) NULL,
	[Recalls] [bit] NULL,
	[Medical_Alert] [bit] NULL,
	[Medical_Alert_Text] [VARCHAR](max) NULL,
	[Sms_Communication] [bit] NULL,
	[Email_Communication] [bit] NULL,
	[Marketing_Opt_In] [bit] NULL,
	[Dentist_Practitioner_Id] [int] NULL,
	[Hygienist_Practitioner_Id] [int] NULL,
	[Payment_Plan_Id] [int] NULL,
	[Acquisition_Source_Id] [VARCHAR](50) NULL,
	[Archived_Reason] [VARCHAR](500) NULL,
	[Consent_To_Share_Accounts] [bit] NULL,
	[Dentist_Recall_Date] [date] NULL,
	[Dentist_Recall_Interval] [int] NULL,
	[Hygienist_Recall_Date] [date] NULL,
	[Hygienist_Recall_Interval] [int] NULL,
	[Recall_Method] [VARCHAR](20) NULL,
	[Family_Id] [VARCHAR](20) NULL,
	[Created_At] [VARCHAR](50) NULL,
	[Updated_At] [VARCHAR](50) NULL,
	[DW_Created_At] [datetime2](6) NOT NULL,
	[DW_Updated_At] [datetime2](6) NOT NULL,
	[_Row_Hash] [varbinary](32) NULL
)
GO