-- Stage.Views.WSeed.sql
-- Re-points all Stage views to WSeed.* warehouse tables written by seed_onelake.py.
-- Run this ONCE before seeding test data.
-- To revert to notebook/live data, run Stage.Views.sql again.

DROP VIEW IF EXISTS [Stage].[Sites]
GO
CREATE VIEW [Stage].[Sites] AS SELECT * FROM WSeed.sites
GO

DROP VIEW IF EXISTS [Stage].[Users]
GO
CREATE VIEW [Stage].[Users] AS SELECT * FROM WSeed.users
GO

DROP VIEW IF EXISTS [Stage].[Practitioners]
GO
CREATE VIEW [Stage].[Practitioners] AS SELECT * FROM WSeed.practitioners
GO

DROP VIEW IF EXISTS [Stage].[Payment_Plans]
GO
CREATE VIEW [Stage].[Payment_Plans] AS SELECT * FROM WSeed.payment_plans
GO

DROP VIEW IF EXISTS [Stage].[Treatments]
GO
CREATE VIEW [Stage].[Treatments] AS SELECT * FROM WSeed.treatments
GO

DROP VIEW IF EXISTS [Stage].[Patients]
GO
CREATE VIEW [Stage].[Patients] AS SELECT * FROM WSeed.patients
GO

DROP VIEW IF EXISTS [Stage].[Appointments]
GO
CREATE VIEW [Stage].[Appointments] AS
SELECT
    tenant_id,
    DW_Stage_Loaded_At,
    id,
    CAST(NULL AS VARCHAR(255))  AS uuid,
    appointment_cancellation_reason_id,
    patient_id,
    CAST(NULL AS VARCHAR(255))  AS patient_name,
    CAST(NULL AS VARCHAR(255))  AS patient_image_url,
    practitioner_id,
    CAST(NULL AS VARCHAR(255))  AS user_id,
    CAST(NULL AS VARCHAR(255))  AS payment_plan_id,
    room_id,
    start_time,
    end_time                    AS finish_time,
    duration,
    reason,
    state,
    CAST(NULL AS VARCHAR(255))  AS notes,
    CAST(NULL AS VARCHAR(255))  AS treatment_description,
    booked_via_api,
    pending_at,
    CAST(NULL AS VARCHAR(255))  AS confirmed_at,
    CAST(NULL AS VARCHAR(255))  AS arrived_at,
    CAST(NULL AS VARCHAR(255))  AS in_surgery_at,
    completed_at,
    cancelled_at,
    did_not_attend_at
FROM WSeed.appointments
GO

DROP VIEW IF EXISTS [Stage].[Invoices]
GO
CREATE VIEW [Stage].[Invoices] AS SELECT * FROM WSeed.invoices
GO

DROP VIEW IF EXISTS [Stage].[Invoice_Items]
GO
CREATE VIEW [Stage].[Invoice_Items] AS SELECT * FROM WSeed.invoice_items
GO

DROP VIEW IF EXISTS [Stage].[Payments]
GO
CREATE VIEW [Stage].[Payments] AS SELECT * FROM WSeed.payments
GO

DROP VIEW IF EXISTS [Stage].[Treatment_Plans]
GO
CREATE VIEW [Stage].[Treatment_Plans] AS SELECT * FROM WSeed.treatment_plans
GO

DROP VIEW IF EXISTS [Stage].[Treatment_Plan_Items]
GO
CREATE VIEW [Stage].[Treatment_Plan_Items] AS SELECT * FROM WSeed.treatment_plan_items
GO

DROP VIEW IF EXISTS [Stage].[Recalls]
GO
CREATE VIEW [Stage].[Recalls] AS SELECT * FROM WSeed.recalls
GO

DROP VIEW IF EXISTS [Stage].[Practitioner_Diary_Entries]
GO
CREATE VIEW [Stage].[Practitioner_Diary_Entries] AS SELECT * FROM WSeed.practitioner_diary_entries
GO

DROP VIEW IF EXISTS [Stage].[Practice]
GO
CREATE VIEW [Stage].[Practice] AS SELECT * FROM WSeed.practice
GO

DROP VIEW IF EXISTS [Stage].[Treatment_Categories]
GO
CREATE VIEW [Stage].[Treatment_Categories] AS SELECT * FROM WSeed.treatment_categories
GO

DROP VIEW IF EXISTS [Stage].[Acquisition_Sources]
GO
CREATE VIEW [Stage].[Acquisition_Sources] AS SELECT * FROM WSeed.acquisition_sources
GO

DROP VIEW IF EXISTS [Stage].[Cancellation_Reasons]
GO
CREATE VIEW [Stage].[Cancellation_Reasons] AS SELECT * FROM WSeed.cancellation_reasons
GO

DROP VIEW IF EXISTS [Stage].[Waiting_Lists]
GO
CREATE VIEW [Stage].[Waiting_Lists] AS SELECT * FROM WSeed.waiting_lists
GO

DROP VIEW IF EXISTS [Stage].[Sundries]
GO
CREATE VIEW [Stage].[Sundries] AS SELECT * FROM WSeed.sundries
GO

DROP VIEW IF EXISTS [Stage].[Contracts]
GO
CREATE VIEW [Stage].[Contracts] AS SELECT * FROM WSeed.contracts
GO

DROP VIEW IF EXISTS [Stage].[Fees]
GO
CREATE VIEW [Stage].[Fees] AS SELECT * FROM WSeed.fees
GO

DROP VIEW IF EXISTS [Stage].[Practitioner_Diary_Breaks]
GO
CREATE VIEW [Stage].[Practitioner_Diary_Breaks] AS SELECT * FROM WSeed.practitioner_diary_breaks
GO

DROP VIEW IF EXISTS [Stage].[NHS_Claims]
GO
CREATE VIEW [Stage].[NHS_Claims] AS SELECT * FROM WSeed.nhs_claims
GO

DROP VIEW IF EXISTS [Stage].[Patient_Stats]
GO
CREATE VIEW [Stage].[Patient_Stats] AS SELECT * FROM WSeed.patient_stats
GO

DROP VIEW IF EXISTS [Stage].[Payment_Allocations]
GO
CREATE VIEW [Stage].[Payment_Allocations] AS SELECT * FROM WSeed.payment_allocations
GO

DROP VIEW IF EXISTS [Stage].[Payment_Explanations]
GO
CREATE VIEW [Stage].[Payment_Explanations] AS SELECT * FROM WSeed.payment_explanations
GO

DROP VIEW IF EXISTS [Stage].[Treatment_Appointments]
GO
CREATE VIEW [Stage].[Treatment_Appointments] AS SELECT * FROM WSeed.treatment_appointments
GO

DROP VIEW IF EXISTS [Stage].[Patient_Referrals]
GO
CREATE VIEW [Stage].[Patient_Referrals] AS SELECT * FROM WSeed.patient_referrals
GO

DROP VIEW IF EXISTS [Stage].[Rooms]
GO
CREATE VIEW [Stage].[Rooms] AS SELECT * FROM WSeed.rooms
GO

-- Accounts is not generated by seed_onelake.py; keep pointing at Lakehouse.
BEGIN TRY
    IF OBJECT_ID('[Stage].[Accounts]', 'V') IS NOT NULL DROP VIEW [Stage].[Accounts];
    EXEC('CREATE VIEW [Stage].[Accounts] AS SELECT * FROM LH_Dentally.dbo.stage_accounts');
END TRY
BEGIN CATCH
    PRINT 'WARN: Stage.Accounts skipped (stage_accounts not in LH_Dentally)';
END CATCH;
GO
