// TabularEditor_KillDeadSpiders.csx
// One-off: removes the retired spider measures (PractitionerSpider + NHS/Scheduling/Treatment)
// that never got off the ground. The Revenue spider (SpiderRevenue) is KEPT -- it is the one the
// report actually uses. Run once in Tabular Editor, then save.
var t = Model.Tables["_Measures"];
var kill = new System.Collections.Generic.HashSet<string> {
    "Spider Avg Chair Utilisation",
    "Spider Avg DNA Score",
    "Spider Avg New Patients",
    "Spider Avg Rev Per Hour",
    "Spider Avg Revenue vs Target",
    "Spider Avg UDA Completion",
    "Spider Chair Utilisation",
    "Spider DNA Score",
    "Spider NHS Avg Rev Per Hour",
    "Spider NHS Avg Revenue",
    "Spider NHS Avg UDA Completion",
    "Spider NHS Avg UDAs Completed",
    "Spider NHS Avg UOAs",
    "Spider NHS Rev Per Hour",
    "Spider NHS Revenue",
    "Spider NHS Tgt Rev Per Hour",
    "Spider NHS Tgt Revenue",
    "Spider NHS Tgt UDA Completion",
    "Spider NHS Tgt UDAs Completed",
    "Spider NHS Tgt UOAs",
    "Spider NHS UDA Completion",
    "Spider NHS UDAs Completed",
    "Spider NHS UOAs",
    "Spider New Patients",
    "Spider Rev Per Hour",
    "Spider Revenue vs Target",
    "Spider Sch Avg BBYL",
    "Spider Sch Avg Cancellation Freq",
    "Spider Sch Avg Chair Utilisation",
    "Spider Sch Avg DNA Score",
    "Spider Sch Avg Days Next 30 Min",
    "Spider Sch Avg Short Notice Cancel",
    "Spider Sch BBYL",
    "Spider Sch Cancellation Freq",
    "Spider Sch Chair Utilisation",
    "Spider Sch DNA Score",
    "Spider Sch Days Next 30 Min",
    "Spider Sch Short Notice Cancel",
    "Spider Sch Tgt BBYL",
    "Spider Sch Tgt Cancellation Freq",
    "Spider Sch Tgt Chair Utilisation",
    "Spider Sch Tgt DNA Score",
    "Spider Sch Tgt Days Next 30 Min",
    "Spider Sch Tgt Short Notice Cancel",
    "Spider Target Chair Utilisation",
    "Spider Target DNA Score",
    "Spider Target New Patients",
    "Spider Target Rev Per Hour",
    "Spider Target Revenue vs Target",
    "Spider Target UDA Completion",
    "Spider Tx Avg Exam Ratio",
    "Spider Tx Avg Open Courses",
    "Spider Tx Avg Open Courses Value",
    "Spider Tx Avg Rev Per Hour",
    "Spider Tx Exam Ratio",
    "Spider Tx Open Courses",
    "Spider Tx Open Courses Value",
    "Spider Tx Rev Per Hour",
    "Spider Tx Tgt Exam Ratio",
    "Spider Tx Tgt Open Courses",
    "Spider Tx Tgt Open Courses Value",
    "Spider Tx Tgt Rev Per Hour",
    "Spider UDA Completion",
};
int removed = 0;
foreach (var m in t.Measures.Where(m => kill.Contains(m.Name)).ToList()) { m.Delete(); removed++; }
Info("Removed " + removed + " retired spider measures (Revenue spider kept).");
