// TabularEditor_ApplyMetricActuals.csx
// -----------------------------------------------------------------------------
// Switches the production KPI-card measures onto the materialised
// Gold.Fact_Metric_Actuals (model table '_Metric Actuals'), and removes the A/B
// compare harness ("… New" / "… Delta" measures).
//
// For each materialised metric it RETARGETS the existing card measure's Expression
// IN PLACE -- the measure's name, format string, display folder and KPI (target/
// variance/background) wiring are all preserved; only the value DAX is replaced.
// Metrics that are NOT materialised keep their original DAX untouched.
//
// GRAIN / BLANK BEHAVIOUR: the measure resolves at the selected site x practitioner
// grain. Where the fact has no row at that grain the measure returns BLANK (not the
// undrilled total) -- e.g. site for plan/aggregate metrics, practitioner for the
// patient stocks. That is intentional: a blank is honest where a breakdown does not
// exist, instead of silently showing the practice-wide total under a filter.
//
// PREREQS:
//   1. The model must contain the '_Metric Actuals' table (PBI view generated by
//      Meta.usp_Create_Gold_Views), refreshed so the latest load is present. Without
//      it every retargeted measure is broken.
//   2. Run this AFTER the per-page measure scripts (which create the measures this
//      retargets) and after TabularEditor_Shared.csx.
//
// Re-runnable. To revert a metric, re-run its per-page script.
// -----------------------------------------------------------------------------

var t = Model.Tables["_Measures"];

// 1) remove the A/B compare harness ------------------------------------------------
int removed = 0;
foreach (var m in t.Measures.Where(m => m.DisplayFolder == "_New Actuals (compare)").ToList())
{ m.Delete(); removed++; }

// 2) production DAX builders -------------------------------------------------------
// Cumulative (sum over the date context): revenue, new patients.
Func<string,string> dCum = key => (@"VAR sel_site = SELECTEDVALUE('List Practice Sites'[pk Practice Site], -1)
VAR sel_prac = SELECTEDVALUE('List Practitioners'[pk Practitioner], -1)
RETURN
CALCULATE(
    SUM('_Metric Actuals'[Numerator]),
    TREATAS(VALUES('List Date'[pk Date]), '_Metric Actuals'[fk Date]),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric]           = ""{key}"",
    '_Metric Actuals'[fk Practice Site] = sel_site,
    '_Metric Actuals'[fk Practitioner]  = sel_prac
)").Replace("{key}", key);

// Rate over the date context: DIVIDE(sum num, sum den) across the selected days.
Func<string,string> dRate = key => (@"VAR sel_site = SELECTEDVALUE('List Practice Sites'[pk Practice Site], -1)
VAR sel_prac = SELECTEDVALUE('List Practitioners'[pk Practitioner], -1)
VAR n = CALCULATE( SUM('_Metric Actuals'[Numerator]),
    TREATAS(VALUES('List Date'[pk Date]), '_Metric Actuals'[fk Date]),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )
VAR d = CALCULATE( SUM('_Metric Actuals'[Denominator]),
    TREATAS(VALUES('List Date'[pk Date]), '_Metric Actuals'[fk Date]),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )
RETURN DIVIDE(n, d)").Replace("{key}", key);

// Snapshot stock: latest snapshot date in the selected period, then the value at it.
Func<string,string> dSnap = key => (@"VAR sel_site = SELECTEDVALUE('List Practice Sites'[pk Practice Site], -1)
VAR sel_prac = SELECTEDVALUE('List Practitioners'[pk Practitioner], -1)
VAR snap_fk = CALCULATE( MAX('_Metric Actuals'[fk Date]),
    TREATAS(VALUES('List Date'[pk Date]), '_Metric Actuals'[fk Date]),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )
RETURN CALCULATE( SUM('_Metric Actuals'[Numerator]),
    '_Metric Actuals'[fk Date] = snap_fk,
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )").Replace("{key}", key);

// Current-state value: ONE row per grain, read date-blind (period-independent).
Func<string,string> dCur = key => (@"VAR sel_site = SELECTEDVALUE('List Practice Sites'[pk Practice Site], -1)
VAR sel_prac = SELECTEDVALUE('List Practitioners'[pk Practitioner], -1)
RETURN CALCULATE( SUM('_Metric Actuals'[Numerator]),
    REMOVEFILTERS('List Date'), REMOVEFILTERS('List Date Grouping'),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )").Replace("{key}", key);

// Current-state rate: date-blind DIVIDE.
Func<string,string> dCurRate = key => (@"VAR sel_site = SELECTEDVALUE('List Practice Sites'[pk Practice Site], -1)
VAR sel_prac = SELECTEDVALUE('List Practitioners'[pk Practitioner], -1)
VAR n = CALCULATE( SUM('_Metric Actuals'[Numerator]), REMOVEFILTERS('List Date'), REMOVEFILTERS('List Date Grouping'),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )
VAR d = CALCULATE( SUM('_Metric Actuals'[Denominator]), REMOVEFILTERS('List Date'), REMOVEFILTERS('List Date Grouping'),
    TREATAS(VALUES('List Practice Sites'[Tenant ID]), '_Metric Actuals'[Tenant ID]),
    '_Metric Actuals'[Metric] = ""{key}"", '_Metric Actuals'[fk Practice Site] = sel_site, '_Metric Actuals'[fk Practitioner] = sel_prac )
RETURN DIVIDE(n, d)").Replace("{key}", key);

// 3) retarget each existing card measure -------------------------------------------
int done = 0, missing = 0;
Action<string,string> apply = (name, dax) => {
    var m = t.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { Warn("measure not found, skipped: " + name); missing++; return; }
    m.Expression = dax; done++;
};

// Cumulative
apply("Total Revenue",                     dCum("total_revenue"));
apply("NHS Revenue",                       dCum("nhs_revenue"));
apply("Private Revenue",                   dCum("private_revenue"));
apply("New Patients",                      dCum("new_patients"));
// Rates (date-context)
apply("DNA Rate",                          dRate("dna_rate"));
apply("Book Before You Leave",             dRate("book_before_you_leave"));
apply("Cancellation Frequency",            dRate("cancellation_frequency"));
apply("Short Notice Cancellation Rate",    dRate("short_notice_cancellation_rate"));
apply("Exam Ratio",                        dRate("exam_ratio"));
apply("Chair Utilisation",                 dRate("chair_utilisation"));
apply("Treatment Acceptance Rate",         dRate("acceptance_rate"));
apply("Average Plan Value",                dRate("avg_plan_value"));
apply("Revenue Per Clinical Hour",         dRate("revenue_per_clinical_hour"));
apply("Discounts",                         dRate("discounts"));
apply("Deposit Value",                     dRate("deposit_ratio"));
// Snapshot stocks (latest in period; blank at practitioner for the patient stocks)
apply("Active Patients",                   dSnap("active_patients"));
apply("Lapsed Patients",                   dSnap("lapsed_patients"));
apply("Overdue Recalls",                   dSnap("overdue_recalls"));
apply("Outstanding Invoices",              dSnap("outstanding_invoices"));
// Current-state values
apply("Open Courses",                      dCur("open_courses"));
apply("Open Courses Value",                dCur("open_courses_value"));
apply("Open Courses Without Appointment",  dCur("open_courses_without_appt"));
apply("Days Until Next 30 Minute Free",    dCur("days_until_30min_free"));
apply("Days Until Next 1 Hour Free",       dCur("days_until_1hr_free"));
// Current-state rates
apply("Email Details Rate",                dCurRate("email_details_rate"));
apply("Phone Details Rate",                dCurRate("phone_details_rate"));
apply("Retention Outlook",                 dCurRate("retention_outlook"));

Info("Metric Actuals applied: " + done + " card measures retargeted onto '_Metric Actuals', "
    + missing + " not found, " + removed + " compare measures removed.");
